name: Continuous Integration
on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  MatrixBuild:
    name: "Qt ${{ matrix.qt_version }} on ${{ matrix.platform }} with ${{ matrix.compiler }}"
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false

      matrix:
        include:
          - platform:   ubuntu-24.04
            packages:   g++-11
            compiler:   gcc-11
            cc_path:    /usr/bin/gcc-11
            cxx_path:   /usr/bin/g++-11
            ninja_path: $IQTA_TOOLS/Ninja/ninja
            qt_version: 5.15.2
            qt_host:    linux
            qt_arch:    gcc_64
            qt_tools:   tools_ninja

          - platform:   ubuntu-24.04
            packages:   g++-12
            compiler:   gcc-12
            cc_path:    /usr/bin/gcc-12
            cxx_path:   /usr/bin/g++-12
            ninja_path: $IQTA_TOOLS/Ninja/ninja
            qt_version: 6.5.3
            qt_host:    linux
            qt_arch:    gcc_64
            qt_tools:   tools_ninja
            qt_modules: 'qt3d'

          - platform:   ubuntu-24.04
            packages:   g++-13
            compiler:   gcc-13
            cc_path:    /usr/bin/gcc-13
            cxx_path:   /usr/bin/g++-13
            ninja_path: $IQTA_TOOLS/Ninja/ninja
            qt_version: 6.8.3
            qt_host:    linux
            qt_arch:    linux_gcc_64
            qt_tools:   tools_ninja
            qt_modules: 'qt3d'

          - platform:   ubuntu-24.04
            packages:   g++-14
            compiler:   gcc-14
            cc_path:    /usr/bin/gcc-14
            cxx_path:   /usr/bin/g++-14
            ninja_path: $IQTA_TOOLS/Ninja/ninja
            qt_version: 6.10.2
            qt_host:    linux
            qt_arch:    linux_gcc_64
            qt_tools:   tools_ninja
            qt_modules: 'qt3d'


          - platform:   ubuntu-24.04
            compiler:   clang-16
            packages:   clang-16 libc++-16-dev libc++abi-16-dev
            cc_path:    /usr/bin/clang-16
            cxx_path:   /usr/bin/clang++-16
            ninja_path: $IQTA_TOOLS/Ninja/ninja
            qt_version: 6.8.3
            qt_host:    linux
            qt_arch:    linux_gcc_64
            qt_tools:   tools_ninja
            qt_modules: 'qt3d'

          - platform:   ubuntu-24.04
            compiler:   clang-20
            packages:   clang-20 libc++-20-dev libc++abi-20-dev
            cc_path:    /usr/bin/clang-20
            cxx_path:   /usr/bin/clang++-20
            ninja_path: $IQTA_TOOLS/Ninja/ninja
            qt_version: 6.10.2
            qt_host:    linux
            qt_arch:    linux_gcc_64
            qt_tools:   tools_ninja
            qt_modules: 'qt3d'


          - platform:   windows-2025
            compiler:   mingw-11.2
            cc_path:    $env:IQTA_TOOLS/mingw1120_64/bin/gcc.exe
            cxx_path:   $env:IQTA_TOOLS/mingw1120_64/bin/g++.exe
            extra_path: $env:IQTA_TOOLS\mingw1120_64\bin;
            ninja_path: $env:IQTA_TOOLS/Ninja/ninja.exe
            qt_version: 5.15.2
            qt_host:    windows
            qt_arch:    win64_mingw81
            qt_tools:   tools_ninja tools_mingw90

          - platform:   windows-2025
            compiler:   mingw-11.2
            cc_path:    $env:IQTA_TOOLS/mingw1310_64/bin/gcc.exe
            cxx_path:   $env:IQTA_TOOLS/mingw1310_64/bin/g++.exe
            extra_path: $env:IQTA_TOOLS\mingw1310_64\bin;
            ninja_path: $env:IQTA_TOOLS/Ninja/ninja.exe
            qt_version: 6.10.2
            qt_host:    windows
            qt_arch:    win64_mingw
            qt_tools:   tools_ninja tools_mingw1310
            qt_modules: 'qt3d'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install packages
        if: matrix.packages
        run: |
          sudo apt update
          sudo apt install ${{ matrix.packages }}

      - name: "Install Qt ${{ matrix.qt_version }}"
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: '==3.3.*'
          version:    ${{ matrix.qt_version }}
          host:       ${{ matrix.qt_host }}
          arch:       ${{ matrix.qt_arch }}
          target:     desktop
          modules:    ${{ matrix.qt_modules }}
          tools:      ${{ matrix.qt_tools }}
          cache:      true

      - name: Set up compiler cache
        uses: chocobo1/setup-ccache-action@v1
        with:
          ccache_options: |
            max_size=100M
          override_cache_key: ccache-linux-${{ matrix.compiler }}-x86_64
          update_packager_index: false

      - name: Configure project
        run: >
          mkdir build && cd build && cmake -GNinja
          -DCMAKE_C_COMPILER:FILEPATH=${{ matrix.cc_path }}
          -DCMAKE_CXX_COMPILER:FILEPATH=${{ matrix.cxx_path }}
          -DCMAKE_MAKE_PROGRAM:FILEPATH=${{ matrix.ninja_path }}
          ..

      - name: Build project
        run: cd build && cmake --build . --target all -- -k0

      - name: Modify PATH for testing
        if: matrix.extra_path
        run: echo "${{ matrix.extra_path }}" >> $env:GITHUB_PATH

      - name: Test project
        run: cd build && ctest --verbose --output-junit test-results.xml
        env:
          QT_QPA_PLATFORM: offscreen

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "test-results-qt-${{ matrix.qt_version }}-${{ matrix.platform }}-${{ matrix.compiler }}"
          path: |
            build/test-results.xml
            build/Testing/Temporary/LastTest.log
