name: Continuous Integration
on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  Build-on-Ubuntu-Qt5:
    name: "Build on Ubuntu for Qt5"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          tools: 'tools_ninja'
          cache: true

      - name: Set up compiler cache
        uses: chocobo1/setup-ccache-action@v1
        with:
          ccache_options: |
            max_size=100M
          override_cache_key: ccache-linux-gcc-x86_64
          update_packager_index: false

      - name: Configure project
        run: >
          mkdir build && cd build && cmake -GNinja
          -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc
          -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++
          -DCMAKE_MAKE_PROGRAM:FILEPATH=$IQTA_TOOLS/Ninja/ninja
          ..

      - name: Build project
        run: cd build && cmake --build . --target all -- -k0

      - name: Test project
        run: cd build && ctest --rerun-failed --output-on-failure
        env:
          QT_QPA_PLATFORM: offscreen

  Build-on-Ubuntu-Qt6:
    name: "Build on Ubuntu for Qt6"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.6.1'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          modules: 'qt3d'
          tools: 'tools_ninja'
          cache: true

      - name: Set up compiler cache
        uses: chocobo1/setup-ccache-action@v1
        with:
          ccache_options: |
            max_size=100M
          override_cache_key: ccache-linux-clang-x86_64
          update_packager_index: false

      - name: Configure project
        run: >
          mkdir build && cd build && cmake -GNinja
          -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang-15
          -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++-15
          -DCMAKE_MAKE_PROGRAM:FILEPATH=$IQTA_TOOLS/Ninja/ninja
          ..

      - name: Build project
        run: cd build && cmake --build . --target all -- -k0

      - name: Test project
        run: cd build && ctest --rerun-failed --output-on-failure
        env:
          QT_QPA_PLATFORM: offscreen

  Build-on-Windows-Qt6:
    name: "Build on Windows for Qt6"
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.6.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          modules: 'qt3d'
          tools: 'tools_mingw90 tools_ninja'
          cache: true

      - name: Set up compiler cache
        uses: chocobo1/setup-ccache-action@v1
        with:
          ccache_options: |
            max_size=100M
          override_cache_key: ccache-windows-mingw64
          windows_compile_environment: msvc # guess "windows_package_manager: choco" would be a better name

      - name: Configure project
        run: >
          mkdir build && cd build && cmake -GNinja
          -DCMAKE_C_COMPILER:FILEPATH=$env:IQTA_TOOLS/mingw1120_64/bin/gcc.exe
          -DCMAKE_CXX_COMPILER:FILEPATH=$env:IQTA_TOOLS/mingw1120_64/bin/g++.exe
          -DCMAKE_MAKE_PROGRAM:FILEPATH=$env:IQTA_TOOLS/Ninja/ninja.exe
          ..

      - name: Build project
        run: cd build && cmake --build . --target all -- -k0

      - name: Test project
        run: cd build && ctest --rerun-failed --output-on-failure
